### ISSUE TITLE
UR AN IDIOT MORE

### ISSUE THREAD

**Issue by TechDudie** [Hardwaregore/you-are-an-idiot#1]
I want YOU ~~for US army~~ to be an idiot

where in the world did you include bomb.js? im confused...

**Comment by TechDudie** [comment]
<img src="https://raw.githubusercontent.com/Hardwaregore/you-are-an-idiot/master/idiot.jpg">

**Comment by TechDudie** [comment]
LOL SO MUCH IRONY HERE

**Comment by Hardwaregore** [comment]
I tried to edit this at school and I ran out of time and then I forgot about it
