### ISSUE TITLE
imaging having this issue stuck on ur home page...

### ISSUE THREAD

**Issue by TechDudie** [Hardwaregore/you-are-an-idiot#2]
![Screen Shot 2022-09-21 at 9 50 41 AM](https://user-images.githubusercontent.com/73961295/191537203-b7289cdd-a11c-4a9f-8f0a-36de368a9eba.png)
AHAHAHAHAHAHAHHAHHAHHHAHAAAAAAAA LOLLLOLOLOLOLOLOOLOLLOLOOLOLLOLOLLOOLLOOLOLLOOLLOLLLLL XDXDXDDXDXDXDXDXDXDXDXDXXDXDXDXDXXDXDXDXXDX HAHAHAHHAHAAHAAHAHAHAHAHAHAHAHA LOLLOOLOLOLOLOLLOLOLOLLOOLLOOLOLOLOOLLLOOLOOOOLOLOLOLLOOLOLOLOLOLOLOLOLOLOOOOOOOLOLOLOOLOLLOLOLOLLOOOOOOOOOOOOOOOL!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
ÂHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁHÃHÂHÂHÁHÀHÄHÅHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÃHÄHÁHÅHÀHĀHÅHÁHÅHÅHÀHĀHÅHÁHÀHÀHÅHÀHĀHÅHÁHĀHÅHÁHĀHÅHÁHÂHÄHÃHÀHÀHĀHÅHÁ

**Comment by TechDudie** [comment]
![Screen Shot 2022-09-21 at 9 54 17 AM](https://user-images.githubusercontent.com/73961295/191538137-f8401d73-59da-447f-90e1-2d8af1875520.png)

THE IMAGE DOESNT EVEN LOADDD

**Comment by Hardwaregore** [comment]
click allow popups

**Comment by TechDudie** [comment]
NOPE

**Comment by Hardwaregore** [comment]
feel free to read this. it will be very helpful

https://github.com/AdoptMeTradingValues/AdoptMeTradingValues.github.io/issues/1#issuecomment-1254912827

**Comment by Jmaxdnix1** [comment]
your version still sucks
